version: 2
updates:
  - package-ecosystem: bundler
    directory: /api
    schedule:
      interval: weekly
    groups:
      ruby-security-and-maintenance:
        patterns: ["*"]

  - package-ecosystem: npm
    directory: /web
    schedule:
      interval: weekly
    groups:
      frontend-security-and-maintenance:
        patterns: ["*"]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
