import type { PracticeChallenge } from '../practiceLab'

const schema = 'CREATE TABLE learners (\n  id INTEGER PRIMARY KEY,\n  name TEXT NOT NULL,\n  village TEXT NOT NULL,\n  completed_lessons INTEGER NOT NULL DEFAULT 0\n);\n'
const seed = "INSERT INTO learners (name, village, completed_lessons) VALUES\n  ('Lina', 'Hagåtña', 6),\n  ('Mia', 'Dededo', 4),\n  ('Kai', 'Yigo', 2),\n  ('Ana', 'Dededo', 5);\n"

function project(title: string, query: string, schemaSource = schema, seedSource = seed) {
  return {
    title: `Practice · ${title}`,
    entryPath: 'main.sql',
    files: [
      { path: 'main.sql', language: 'sql' as const, content: query },
      { path: 'schema.sql', language: 'sql' as const, content: schemaSource },
      { path: 'seed.sql', language: 'sql' as const, content: seedSource },
    ],
  }
}

export const SQL_CHALLENGES: PracticeChallenge[] = [
  {
    id: 'sql-select-names', kind: 'sql', title: 'Choose two columns', difficulty: 'Starter',
    summary: 'Return only the learner names and villages.', concepts: ['SELECT', 'FROM', 'columns'],
    instructions: ['Select `name` and `village`.', 'Read rows from `learners`.'],
    hints: ['Separate the two column names with a comma.', 'Put the table after `FROM`.'],
    project: project('Choose Columns', 'SELECT *\nFROM learners;\n'),
    checks: [{ filePath: 'main.sql', label: 'Select name and village from learners', pattern: /SELECT\s+name\s*,\s*village\s+FROM\s+learners/i, ignoreStrings: true }],
    expectedOutput: 'name | village\nLina | Hagåtña\nMia | Dededo\nKai | Yigo\nAna | Dededo',
  },
  {
    id: 'sql-filter-progress', kind: 'sql', title: 'Filter learner progress', difficulty: 'Starter',
    summary: 'Keep learners who completed at least five lessons.', concepts: ['WHERE', 'comparison'],
    instructions: ['Select `name` and `completed_lessons`.', 'Keep rows where completed lessons are at least 5.', 'Order by name.'],
    hints: ['“At least” uses `>=`.', '`WHERE` comes before `ORDER BY`.'],
    project: project('Filter Progress', 'SELECT name, completed_lessons\nFROM learners\nORDER BY name;\n'),
    checks: [{ filePath: 'main.sql', label: 'Filter for at least five lessons', pattern: /WHERE\s+completed_lessons\s*>=\s*5/i, ignoreStrings: true }],
    expectedOutput: 'name | completed_lessons\nAna | 5\nLina | 6',
  },
  {
    id: 'sql-sort-lessons', kind: 'sql', title: 'Sort highest first', difficulty: 'Starter',
    summary: 'Place the most completed lessons first.', concepts: ['ORDER BY', 'DESC'],
    instructions: ['Select each name and lesson count.', 'Sort completed lessons in descending order.'],
    hints: ['Use `ORDER BY completed_lessons DESC`.', '`DESC` means descending; `ASC` means ascending.'],
    project: project('Sort Lessons', 'SELECT name, completed_lessons\nFROM learners;\n'),
    checks: [{ filePath: 'main.sql', label: 'Sort lesson counts descending', pattern: /ORDER\s+BY\s+completed_lessons\s+DESC/i, ignoreStrings: true }],
    expectedOutput: 'name | completed_lessons\nLina | 6\nAna | 5\nMia | 4\nKai | 2',
  },
  {
    id: 'sql-alias-points', kind: 'sql', title: 'Calculate practice points', difficulty: 'Starter',
    summary: 'Calculate two points per completed lesson and name the result.', concepts: ['expressions', 'aliases'],
    instructions: ['Select `name`.', 'Multiply `completed_lessons` by 2.', 'Alias the calculation as `practice_points`.', 'Order by name.'],
    hints: ['Use `completed_lessons * 2 AS practice_points`.', 'Put the calculated expression in the SELECT list.'],
    project: project('Practice Points', 'SELECT name\nFROM learners\nORDER BY name;\n'),
    checks: [{ filePath: 'main.sql', label: 'Calculate and alias practice points', pattern: /completed_lessons\s*\*\s*2\s+AS\s+practice_points/i, ignoreStrings: true }],
    expectedOutput: 'name | practice_points\nAna | 10\nKai | 4\nLina | 12\nMia | 8',
  },
  {
    id: 'sql-count-learners', kind: 'sql', title: 'Count learners', difficulty: 'Starter',
    summary: 'Return one row containing the number of learners.', concepts: ['COUNT', 'aliases'],
    instructions: ['Count every row in `learners`.', 'Alias the value as `learner_count`.'],
    hints: ['`COUNT(*)` counts rows.', 'An alias gives the result column a readable name.'],
    project: project('Count Learners', 'SELECT name\nFROM learners;\n'),
    checks: [{ filePath: 'main.sql', label: 'Count rows with the requested alias', pattern: /SELECT\s+COUNT\s*\(\s*\*\s*\)\s+AS\s+learner_count\s+FROM\s+learners/i, ignoreStrings: true }],
    expectedOutput: 'learner_count\n4',
  },
  {
    id: 'sql-group-villages', kind: 'sql', title: 'Summarize villages', difficulty: 'Builder',
    summary: 'Create one count for each village.', concepts: ['GROUP BY', 'COUNT'],
    instructions: ['Select `village` and `COUNT(*) AS learner_count`.', 'Group by village.', 'Order by village.'],
    hints: ['Every non-aggregate selected column belongs in `GROUP BY`.', 'Keep `ORDER BY` after the grouping clause.'],
    project: project('Village Summary', 'SELECT village\nFROM learners\nORDER BY village;\n'),
    checks: [{ filePath: 'main.sql', label: 'Count learners by village', pattern: /COUNT\s*\(\s*\*\s*\)[\s\S]*GROUP\s+BY\s+village/i, ignoreStrings: true }],
    expectedOutput: 'village | learner_count\nDededo | 2\nHagåtña | 1\nYigo | 1',
  },
  {
    id: 'sql-average-progress', kind: 'sql', title: 'Average the progress', difficulty: 'Builder',
    summary: 'Calculate the average completed lesson count.', concepts: ['AVG', 'ROUND'],
    instructions: ['Average `completed_lessons`.', 'Round to one decimal place.', 'Alias it as `average_lessons`.'],
    hints: ['Nest `AVG(...)` inside `ROUND(..., 1)`.', 'Alias the final expression, not the inner average.'],
    project: project('Average Progress', 'SELECT completed_lessons\nFROM learners;\n'),
    checks: [{ filePath: 'main.sql', label: 'Round the average to one decimal', pattern: /ROUND\s*\(\s*AVG\s*\(\s*completed_lessons\s*\)\s*,\s*1\s*\)\s+AS\s+average_lessons/i, ignoreStrings: true }],
    expectedOutput: 'average_lessons\n4.3',
  },
  {
    id: 'sql-find-name', kind: 'sql', title: 'Find names by pattern', difficulty: 'Builder',
    summary: 'Use a text pattern to find names ending in “a”.', concepts: ['LIKE', 'patterns'],
    instructions: ['Select `name`.', 'Keep names matching `%a`.', 'Order by name.'],
    hints: ['In a LIKE pattern, `%` means any amount of text.', 'Put the pattern in quotes because it is text.'],
    project: project('Name Pattern', 'SELECT name\nFROM learners\nORDER BY name;\n'),
    checks: [{ filePath: 'main.sql', label: 'Filter names ending in a', pattern: /WHERE\s+name\s+LIKE\s+['"]%a['"]/i }],
    expectedOutput: 'name\nAna\nLina\nMia',
  },
  {
    id: 'sql-join-badges', kind: 'sql', title: 'Join learner badges', difficulty: 'Builder',
    summary: 'Connect learners to badges through a learner ID.', concepts: ['JOIN', 'ON', 'aliases'],
    instructions: ['Join `badges` to `learners` on learner ID.', 'Select learner name and badge.', 'Order by learner name and badge.'],
    hints: ['Use aliases such as `learners AS l` and `badges AS b`.', 'Match `b.learner_id` with `l.id` in the ON clause.'],
    project: project('Join Badges', 'SELECT l.name, b.badge\nFROM learners AS l\n-- Add the join.\nORDER BY l.name, b.badge;\n', `${schema}\nCREATE TABLE badges (learner_id INTEGER NOT NULL, badge TEXT NOT NULL);\n`, `${seed}\nINSERT INTO badges VALUES (1, 'First Query'), (1, 'Data Helper'), (2, 'First Query');\n`),
    checks: [{ filePath: 'main.sql', label: 'Join badges on matching learner IDs', pattern: /JOIN\s+badges\s+AS\s+b\s+ON\s+b\.learner_id\s*=\s*l\.id/i, ignoreStrings: true }],
    expectedOutput: 'name | badge\nLina | Data Helper\nLina | First Query\nMia | First Query',
  },
  {
    id: 'sql-left-join-badges', kind: 'sql', title: 'Keep learners without badges', difficulty: 'Builder',
    summary: 'Use a left join so unmatched learners remain visible.', concepts: ['LEFT JOIN', 'NULL', 'COALESCE'],
    instructions: ['Left join badges to learners.', 'Show `No badge` with `COALESCE` when a badge is missing.', 'Order by learner name.'],
    hints: ['A `LEFT JOIN` preserves every row from the left table.', '`COALESCE` returns its fallback when the badge is NULL.'],
    project: project('Keep Unmatched Learners', "SELECT l.name, COALESCE(b.badge, 'No badge') AS badge\nFROM learners AS l\nJOIN badges AS b ON b.learner_id = l.id\nORDER BY l.name;\n", `${schema}\nCREATE TABLE badges (learner_id INTEGER NOT NULL, badge TEXT NOT NULL);\n`, `${seed}\nINSERT INTO badges VALUES (1, 'First Query'), (2, 'First Query');\n`),
    checks: [{ filePath: 'main.sql', label: 'Use a left join', pattern: /LEFT\s+JOIN\s+badges/i, ignoreStrings: true }, { filePath: 'main.sql', label: 'Provide a fallback for missing badges', pattern: /COALESCE\s*\(\s*b\.badge\s*,\s*['"]No badge['"]\s*\)/i }],
    expectedOutput: 'name | badge\nAna | No badge\nKai | No badge\nLina | First Query\nMia | First Query',
  },
  {
    id: 'sql-above-average', kind: 'sql', title: 'Find above-average learners', difficulty: 'Stretch',
    summary: 'Use a subquery to compare each learner with the class average.', concepts: ['subqueries', 'AVG', 'WHERE'],
    instructions: ['Select name and completed lessons.', 'Compare each value with a subquery that calculates the average.', 'Order highest first.'],
    hints: ['The subquery is `(SELECT AVG(completed_lessons) FROM learners)`.', 'Place that subquery on the right side of `>`.'],
    project: project('Above Average', 'SELECT name, completed_lessons\nFROM learners\nORDER BY completed_lessons DESC;\n'),
    checks: [{ filePath: 'main.sql', label: 'Compare against an average subquery', pattern: /WHERE\s+completed_lessons\s*>\s*\(\s*SELECT\s+AVG\s*\(\s*completed_lessons\s*\)\s+FROM\s+learners\s*\)/i, ignoreStrings: true }],
    expectedOutput: 'name | completed_lessons\nLina | 6\nAna | 5',
  },
  {
    id: 'sql-progress-cte', kind: 'sql', title: 'Build a progress CTE', difficulty: 'Stretch',
    summary: 'Name an intermediate query and reuse it.', concepts: ['CTE', 'WITH', 'CASE'],
    instructions: ['Create a CTE named `progress`.', 'Use a CASE expression that labels 5 or more lessons as `ready` and the rest as `growing`.', 'Select ready learners from the CTE ordered by name.'],
    hints: ['Begin with `WITH progress AS (...)`.', 'Use CASE to produce the status.'],
    project: project('Progress CTE', 'SELECT name\nFROM learners\nORDER BY name;\n'),
    checks: [{ filePath: 'main.sql', label: 'Define and query the progress CTE', pattern: /WITH\s+progress\s+AS\s*\([\s\S]*CASE[\s\S]*\)[\s\S]*FROM\s+progress/i, ignoreStrings: true }, { filePath: 'main.sql', label: 'Filter the ready status', pattern: /WHERE\s+status\s*=\s*['"]ready['"]/i }],
    expectedOutput: 'name\nAna\nLina',
  },
  {
    id: 'sql-ranked-learners', kind: 'sql', title: 'Rank learners', difficulty: 'Stretch',
    summary: 'Use a window function to rank progress without collapsing rows.', concepts: ['window functions', 'RANK', 'OVER'],
    instructions: ['Select name and completed lessons.', 'Add `RANK()` ordered by completed lessons descending.', 'Alias it as `progress_rank`.'],
    hints: ['Write `RANK() OVER (ORDER BY completed_lessons DESC)`.', 'Alias the window expression as `progress_rank`.'],
    project: project('Rank Learners', 'SELECT name, completed_lessons\nFROM learners\nORDER BY completed_lessons DESC;\n'),
    checks: [{ filePath: 'main.sql', label: 'Rank lesson progress descending', pattern: /RANK\s*\(\s*\)\s+OVER\s*\(\s*ORDER\s+BY\s+completed_lessons\s+DESC\s*\)\s+AS\s+progress_rank/i, ignoreStrings: true }],
    expectedOutput: 'name | completed_lessons | progress_rank\nLina | 6 | 1\nAna | 5 | 2\nMia | 4 | 3\nKai | 2 | 4',
  },
  {
    id: 'sql-update-kai', kind: 'sql', title: 'Update one learner safely', difficulty: 'Stretch',
    summary: 'Change one intended row with a precise condition.', concepts: ['UPDATE', 'SET', 'WHERE'],
    instructions: ['Increase Kai’s completed lessons by 1.', 'Use a WHERE clause that targets only Kai.'],
    hints: ['Set the column to itself plus 1.', 'Always inspect a WHERE clause before changing data.'],
    project: project('Update Kai', "UPDATE learners\nSET completed_lessons = completed_lessons\nWHERE name = 'Kai';\n"),
    checks: [{ filePath: 'main.sql', label: 'Increase completed lessons by one', pattern: /SET\s+completed_lessons\s*=\s*completed_lessons\s*\+\s*1/i, ignoreStrings: true }, { filePath: 'main.sql', label: 'Target only Kai', pattern: /WHERE\s+name\s*=\s*['"]Kai['"]/i }],
    expectedOutput: '1 row changed',
  },
  {
    id: 'sql-relational-schema', kind: 'sql', title: 'Design a related badges table', difficulty: 'Stretch',
    summary: 'Add a related table with a key and query it through a join.', concepts: ['schema', 'foreign keys', 'JOIN'],
    instructions: ['In schema.sql, create `badges` with `learner_id INTEGER NOT NULL` and `badge TEXT NOT NULL`.', 'Add a foreign key referencing `learners(id)`.', 'In main.sql, join learners and badges on learner ID.'],
    hints: ['Add `FOREIGN KEY (learner_id) REFERENCES learners(id)` inside CREATE TABLE.', 'Reset happens automatically after schema.sql changes.'],
    project: project('Related Badge Schema', 'SELECT l.name, b.badge\nFROM learners AS l\nJOIN badges AS b ON b.learner_id = l.id\nORDER BY l.name;\n', `${schema}\n-- Create the badges table here.\n`, `${seed}\nINSERT INTO badges (learner_id, badge) VALUES (1, 'First Query');\n`),
    checks: [
      { filePath: 'schema.sql', label: 'Create the badges table and required columns', pattern: /CREATE\s+TABLE\s+badges\s*\([\s\S]*learner_id\s+INTEGER\s+NOT\s+NULL[\s\S]*badge\s+TEXT\s+NOT\s+NULL/i, ignoreStrings: true },
      { filePath: 'schema.sql', label: 'Reference the learner primary key', pattern: /FOREIGN\s+KEY\s*\(\s*learner_id\s*\)\s+REFERENCES\s+learners\s*\(\s*id\s*\)/i, ignoreStrings: true },
      { filePath: 'main.sql', label: 'Join badges to learners', pattern: /JOIN\s+badges\s+AS\s+b\s+ON\s+b\.learner_id\s*=\s*l\.id/i, ignoreStrings: true },
    ],
    expectedOutput: 'name | badge\nLina | First Query',
  },
]
