import type { PracticeChallenge } from '../practiceLab'

export const TYPESCRIPT_CHALLENGES: PracticeChallenge[] = [
  {
    id: 'typescript-typed-greeting', kind: 'typescript', title: 'Type a greeting', difficulty: 'Starter',
    summary: 'Add simple annotations to text and number values.',
    concepts: ['type annotations', 'strings', 'numbers'],
    instructions: ['Set `name` to "Lina" and annotate it as `string`.', 'Set `lessons` to 4 and annotate it as `number`.', 'Run the project to print both values.'],
    hints: ['Write an annotation after a variable name: `name: string`.', 'A numeric value does not use quotes.'],
    project: { title: 'Practice · TypeScript Greeting', entryPath: 'main.ts', files: [{ path: 'main.ts', language: 'typescript', content: 'const name: string = "friend"\nconst lessons: number = 0\n\nconsole.log(`Hafa adai, ${name}!`)\nconsole.log(`Lessons: ${lessons}`)\n' }] },
    checks: [
      { filePath: 'main.ts', label: 'Type and set name to Lina', pattern: /\bname\s*:\s*string\s*=\s*["']Lina["']/ },
      { filePath: 'main.ts', label: 'Type and set lessons to 4', pattern: /\blessons\s*:\s*number\s*=\s*4\b/ },
    ],
    expectedOutput: 'Hafa adai, Lina!\nLessons: 4',
  },
  {
    id: 'typescript-order-total', kind: 'typescript', title: 'Calculate a typed total', difficulty: 'Starter',
    summary: 'Use number annotations and arithmetic together.',
    concepts: ['numbers', 'arithmetic', 'inference'],
    instructions: ['Set `price` to 6 and `quantity` to 3.', 'Calculate `total` by multiplying them.', 'Print `Total: 18`.'],
    hints: ['Both inputs can use the `number` type.', 'TypeScript can infer the type of `total` from multiplication.'],
    project: { title: 'Practice · TypeScript Total', entryPath: 'main.ts', files: [{ path: 'main.ts', language: 'typescript', content: 'const price: number = 0\nconst quantity: number = 0\nconst total = 0\n\nconsole.log(`Total: ${total}`)\n' }] },
    checks: [
      { filePath: 'main.ts', label: 'Set price to 6', pattern: /\bprice\s*:\s*number\s*=\s*6\b/ },
      { filePath: 'main.ts', label: 'Set quantity to 3', pattern: /\bquantity\s*:\s*number\s*=\s*3\b/ },
      { filePath: 'main.ts', label: 'Multiply price by quantity', pattern: /\btotal(?:\s*:\s*number)?\s*=\s*price\s*\*\s*quantity\b/, ignoreStrings: true },
    ],
    expectedOutput: 'Total: 18',
  },
  {
    id: 'typescript-status-union', kind: 'typescript', title: 'Limit a status', difficulty: 'Starter',
    summary: 'Use a string-literal union to allow only intended status values.',
    concepts: ['unions', 'literal types', 'variables'],
    instructions: ['Declare `status` as `"draft" | "ready"`.', 'Start it at `"draft"`.', 'Change it to `"ready"` and print it.'],
    hints: ['Join allowed types with `|`.', 'Use `let` because the value changes.'],
    project: { title: 'Practice · TypeScript Status', entryPath: 'main.ts', files: [{ path: 'main.ts', language: 'typescript', content: 'let status = "draft"\n\n// Change the status when the work is ready.\nconsole.log(status)\n' }] },
    checks: [
      { filePath: 'main.ts', label: 'Declare the two-choice status union', pattern: /\bstatus\s*:\s*["']draft["']\s*\|\s*["']ready["']/ },
      { filePath: 'main.ts', label: 'Change status to ready', pattern: /\bstatus\s*=\s*["']ready["']/, ignoreStrings: true },
    ],
    expectedOutput: 'ready',
  },
  {
    id: 'typescript-array-stops', kind: 'typescript', title: 'Type a stop list', difficulty: 'Starter',
    summary: 'Describe an array whose every item is text.',
    concepts: ['arrays', 'string types', 'indexing'],
    instructions: ['Create a `string[]` named `stops` with Hagåtña, Tamuning, and Dededo.', 'Print the first stop.', 'Print the array length.'],
    hints: ['Place `string[]` after the variable name.', 'Array positions begin at 0.'],
    project: { title: 'Practice · TypeScript Stops', entryPath: 'main.ts', files: [{ path: 'main.ts', language: 'typescript', content: 'const stops: string[] = []\n\nconsole.log(`First stop: ${stops[0]}`)\nconsole.log(`Total stops: ${stops.length}`)\n' }] },
    checks: [
      { filePath: 'main.ts', label: 'Create a typed three-stop array', pattern: /\bstops\s*:\s*string\s*\[\s*\]\s*=\s*\[\s*["']Hagatna["']\s*,\s*["']Tamuning["']\s*,\s*["']Dededo["']\s*\]/, matchLearnerText: true },
      { filePath: 'main.ts', label: 'Read the first item and array length', pattern: /stops\s*\[\s*0\s*\][\s\S]*stops\.length/ },
    ],
    expectedOutput: 'First stop: Hagåtña\nTotal stops: 3',
  },
  {
    id: 'typescript-welcome-function', kind: 'typescript', title: 'Type a welcome function', difficulty: 'Starter',
    summary: 'Annotate a function parameter and return value.',
    concepts: ['functions', 'parameters', 'return types'],
    instructions: ['Define `welcome` with a string `name` parameter.', 'Declare that it returns a string.', 'Call it with "Mia" and print the result.'],
    hints: ['Use `function welcome(name: string): string`.', 'Return a template string that uses `name`.'],
    project: { title: 'Practice · TypeScript Welcome', entryPath: 'main.ts', files: [{ path: 'main.ts', language: 'typescript', content: '// Define welcome here.\n\nconsole.log("Welcome, friend!")\n' }] },
    checks: [
      { filePath: 'main.ts', label: 'Define a typed welcome function', pattern: /\bfunction\s+welcome\s*\(\s*name\s*:\s*string\s*\)\s*:\s*string\b/, ignoreStrings: true },
      { filePath: 'main.ts', label: 'Call welcome with Mia', pattern: /\bwelcome\s*\(\s*["']Mia["']\s*\)/ },
    ],
    expectedOutput: 'Welcome, Mia!',
  },
  {
    id: 'typescript-learner-interface', kind: 'typescript', title: 'Describe a learner', difficulty: 'Builder',
    summary: 'Use an interface to require a consistent object shape.',
    concepts: ['interfaces', 'objects', 'properties'],
    instructions: ['Create a `Learner` interface with `name: string` and `lessons: number`.', 'Create `learner: Learner` for Lina with 4 lessons.', 'Print `Lina: 4`.'],
    hints: ['Interface properties are separated by new lines or semicolons.', 'Annotate the object variable with `: Learner`.'],
    project: { title: 'Practice · TypeScript Learner', entryPath: 'main.ts', files: [{ path: 'main.ts', language: 'typescript', content: '// Define the Learner interface.\n\nconst learner = { name: "friend", lessons: 0 }\nconsole.log(`${learner.name}: ${learner.lessons}`)\n' }] },
    checks: [
      { filePath: 'main.ts', label: 'Define the Learner interface', pattern: /\binterface\s+Learner\s*\{[^}]*name\s*:\s*string[^}]*lessons\s*:\s*number[^}]*\}/, ignoreStrings: true },
      { filePath: 'main.ts', label: 'Create a typed Lina learner', pattern: /\blearner\s*:\s*Learner\s*=\s*\{[^}]*name\s*:\s*["']Lina["'][^}]*lessons\s*:\s*4\b/ },
    ],
    expectedOutput: 'Lina: 4',
  },
  {
    id: 'typescript-optional-mentor', kind: 'typescript', title: 'Add an optional mentor', difficulty: 'Builder',
    summary: 'Model a property that may be absent and provide a fallback.',
    concepts: ['optional properties', 'nullish coalescing', 'interfaces'],
    instructions: ['Define `mentor?: string` on `Learner`.', 'Keep the learner object without a mentor.', 'Print `Independent` with `??` as the fallback.'],
    hints: ['Put `?` after the property name.', 'Use `learner.mentor ?? "Independent"`.'],
    project: { title: 'Practice · Optional Mentor', entryPath: 'main.ts', files: [{ path: 'main.ts', language: 'typescript', content: 'interface Learner {\n  name: string\n}\n\nconst learner: Learner = { name: "Ana" }\nconsole.log("Add fallback")\n' }] },
    checks: [
      { filePath: 'main.ts', label: 'Declare an optional mentor', pattern: /\bmentor\s*\?\s*:\s*string\b/, ignoreStrings: true },
      { filePath: 'main.ts', label: 'Use a nullish fallback', pattern: /learner\.mentor\s*\?\?\s*["']Independent["']/ },
    ],
    expectedOutput: 'Independent',
  },
  {
    id: 'typescript-narrow-id', kind: 'typescript', title: 'Narrow an ID', difficulty: 'Builder',
    summary: 'Safely handle a value that can be text or a number.',
    concepts: ['narrowing', 'typeof', 'unions'],
    instructions: ['Accept `string | number` in `formatId`.', 'Use `typeof` to detect a number.', 'Return `#42` for 42 and uppercase text otherwise.'],
    hints: ['Check `typeof id === "number"`.', 'Numbers have `.toFixed`; strings have `.toUpperCase`.'],
    project: { title: 'Practice · TypeScript Narrowing', entryPath: 'main.ts', files: [{ path: 'main.ts', language: 'typescript', content: 'function formatId(id: string | number): string {\n  return String(id)\n}\n\nconsole.log(formatId(42))\nconsole.log(formatId("guam"))\n' }] },
    checks: [
      { filePath: 'main.ts', label: 'Narrow the number branch with typeof', pattern: /typeof\s+id\s*===\s*["']number["']/, ignoreStrings: true },
      { filePath: 'main.ts', label: 'Format both number and string branches', pattern: /id\.toFixed\s*\([^)]+\)[\s\S]*id\.toUpperCase\s*\(/, ignoreStrings: true },
    ],
    expectedOutput: '#42\nGUAM',
  },
  {
    id: 'typescript-map-scores', kind: 'typescript', title: 'Transform typed scores', difficulty: 'Builder',
    summary: 'Let array types flow into a mapping callback.',
    concepts: ['arrays', 'map', 'inference'],
    instructions: ['Create `scores: number[]` with 7, 9, and 10.', 'Use `.map` to add 1 to every score.', 'Print `8,10,11`.'],
    hints: ['`.map((score) => score + 1)` returns a new array.', 'Use `.join(",")` for the requested output.'],
    project: { title: 'Practice · TypeScript Scores', entryPath: 'main.ts', files: [{ path: 'main.ts', language: 'typescript', content: 'const scores: number[] = []\nconst improved = scores\n\nconsole.log(improved.join(","))\n' }] },
    checks: [
      { filePath: 'main.ts', label: 'Create the typed scores array', pattern: /\bscores\s*:\s*number\s*\[\s*\]\s*=\s*\[\s*7\s*,\s*9\s*,\s*10\s*\]/ },
      { filePath: 'main.ts', label: 'Map each score to score plus one', pattern: /scores\.map\s*\(\s*\(?\s*score\s*\)?\s*=>\s*score\s*\+\s*1\s*\)/, ignoreStrings: true },
    ],
    expectedOutput: '8,10,11',
  },
  {
    id: 'typescript-local-module', kind: 'typescript', title: 'Share a typed greeting', difficulty: 'Builder',
    summary: 'Export a typed function from one project file and import it from another.',
    concepts: ['modules', 'imports', 'exports', 'multi-file projects'],
    instructions: ['Export `greeting(name: string): string` from `greeting.ts`.', 'Import it into `main.ts` with a relative path.', 'Print the greeting for Guam.'],
    hints: ['Begin the helper with `export function greeting`.', 'Import from `"./greeting"`; npm packages are not available.'],
    project: { title: 'Practice · TypeScript Module', entryPath: 'main.ts', files: [
      { path: 'main.ts', language: 'typescript', content: '// Import greeting from ./greeting\n\nconsole.log("Hafa adai, Guam!")\n' },
      { path: 'greeting.ts', language: 'typescript', content: '// Export a typed greeting function.\n' },
    ] },
    checks: [
      { filePath: 'greeting.ts', label: 'Export a typed greeting function', pattern: /\bexport\s+function\s+greeting\s*\(\s*name\s*:\s*string\s*\)\s*:\s*string\b/, ignoreStrings: true },
      { filePath: 'main.ts', label: 'Import the local greeting', pattern: /\bimport\s*\{\s*greeting\s*\}\s*from\s*["']\.\/greeting["']/ },
      { filePath: 'main.ts', label: 'Call greeting with Guam', pattern: /\bgreeting\s*\(\s*["']Guam["']\s*\)/ },
    ],
    expectedOutput: 'Hafa adai, Guam!',
  },
  {
    id: 'typescript-generic-first', kind: 'typescript', title: 'Keep the first item type', difficulty: 'Stretch',
    summary: 'Use a generic helper without losing the caller’s item type.',
    concepts: ['generics', 'type parameters', 'undefined'],
    instructions: ['Define `first<T>(items: T[]): T | undefined`.', 'Return the first item.', 'Print the first place in the provided array.'],
    hints: ['Put `<T>` after the function name.', 'An empty array makes the return value possibly `undefined`.'],
    project: { title: 'Practice · TypeScript Generic', entryPath: 'main.ts', files: [{ path: 'main.ts', language: 'typescript', content: '// Define first<T> here.\n\nconst places = ["Hagåtña", "Dededo"]\nconsole.log("first place")\n' }] },
    checks: [
      { filePath: 'main.ts', label: 'Define the generic first signature', pattern: /\bfunction\s+first\s*<\s*T\s*>\s*\(\s*items\s*:\s*T\s*\[\s*\]\s*\)\s*:\s*T\s*\|\s*undefined\b/, ignoreStrings: true },
      { filePath: 'main.ts', label: 'Call first with places', pattern: /\bfirst\s*\(\s*places\s*\)/, ignoreStrings: true },
    ],
    expectedOutput: 'Hagåtña',
  },
  {
    id: 'typescript-shape-union', kind: 'typescript', title: 'Calculate shape areas', difficulty: 'Stretch',
    summary: 'Narrow a discriminated union by its literal `kind` property.',
    concepts: ['discriminated unions', 'interfaces', 'narrowing'],
    instructions: ['Define circle and square object types with different `kind` literals.', 'Create a `Shape` union.', 'Narrow on `shape.kind` and return the correct area.'],
    hints: ['A circle kind can be typed as the literal `"circle"`.', 'In the square branch, multiply `size * size`.'],
    project: { title: 'Practice · TypeScript Shapes', entryPath: 'main.ts', files: [{ path: 'main.ts', language: 'typescript', content: 'type Circle = { kind: "circle"; radius: number }\ntype Square = { kind: "square"; size: number }\n\n// Create Shape and area here.\n\nconsole.log(0)\n' }] },
    checks: [
      { filePath: 'main.ts', label: 'Create the Shape union', pattern: /\btype\s+Shape\s*=\s*Circle\s*\|\s*Square\b/, ignoreStrings: true },
      { filePath: 'main.ts', label: 'Narrow with the kind property', pattern: /shape\.kind\s*===\s*["']circle["']/, ignoreStrings: true },
      { filePath: 'main.ts', label: 'Use square size in the other branch', pattern: /shape\.size\s*\*\s*shape\.size/, ignoreStrings: true },
    ],
  },
  {
    id: 'typescript-readonly-config', kind: 'typescript', title: 'Protect configuration', difficulty: 'Stretch',
    summary: 'Prevent accidental reassignment of a stable object property.',
    concepts: ['readonly', 'interfaces', 'immutability'],
    instructions: ['Define `AppConfig` with `readonly island: string` and `maxLearners: number`.', 'Create a matching `config` object.', 'Print `Guam: 24`.'],
    hints: ['Place `readonly` before the property name.', 'Readonly protects reassignment through that typed property.'],
    project: { title: 'Practice · TypeScript Config', entryPath: 'main.ts', files: [{ path: 'main.ts', language: 'typescript', content: '// Define AppConfig here.\n\nconst config = { island: "Guam", maxLearners: 24 }\nconsole.log(`${config.island}: ${config.maxLearners}`)\n' }] },
    checks: [
      { filePath: 'main.ts', label: 'Declare a readonly island property', pattern: /\binterface\s+AppConfig\s*\{[^}]*readonly\s+island\s*:\s*string[^}]*maxLearners\s*:\s*number/, ignoreStrings: true },
      { filePath: 'main.ts', label: 'Type config as AppConfig', pattern: /\bconfig\s*:\s*AppConfig\s*=/, ignoreStrings: true },
    ],
    expectedOutput: 'Guam: 24',
  },
  {
    id: 'typescript-unknown-message', kind: 'typescript', title: 'Handle an unknown error', difficulty: 'Stretch',
    summary: 'Narrow an unknown value before reading its details.',
    concepts: ['unknown', 'instanceof', 'errors'],
    instructions: ['Accept `value: unknown` in `errorMessage`.', 'Return `.message` only when it is an `Error`.', 'Return `Unknown problem` otherwise.'],
    hints: ['Use `value instanceof Error`.', 'The check narrows `value` inside its branch.'],
    project: { title: 'Practice · TypeScript Unknown', entryPath: 'main.ts', files: [{ path: 'main.ts', language: 'typescript', content: 'function errorMessage(value: unknown): string {\n  return "Unknown problem"\n}\n\nconsole.log(errorMessage(new Error("Try again")))\n' }] },
    checks: [
      { filePath: 'main.ts', label: 'Narrow unknown with instanceof Error', pattern: /value\s+instanceof\s+Error/, ignoreStrings: true },
      { filePath: 'main.ts', label: 'Return the narrowed message', pattern: /return\s+value\.message\b/, ignoreStrings: true },
    ],
    expectedOutput: 'Try again',
  },
  {
    id: 'typescript-service-queue', kind: 'typescript', title: 'Sort a service queue', difficulty: 'Stretch',
    summary: 'Combine an interface, typed arrays, and a comparator.',
    concepts: ['interfaces', 'sorting', 'callbacks', 'arrays'],
    instructions: ['Define `ServiceRequest` with `name: string` and `priority: number`.', 'Type the provided `requests` array.', 'Sort highest priority first and print each name.'],
    hints: ['Annotate with `ServiceRequest[]`.', 'Descending priority uses `(a, b) => b.priority - a.priority`.'],
    project: { title: 'Practice · TypeScript Queue', entryPath: 'main.ts', files: [{ path: 'main.ts', language: 'typescript', content: '// Define ServiceRequest.\n\nconst requests = [\n  { name: "Card question", priority: 1 },\n  { name: "Password reset", priority: 3 },\n  { name: "Address update", priority: 2 },\n]\n\n// Sort and print each request name.\n' }] },
    checks: [
      { filePath: 'main.ts', label: 'Define the service request shape', pattern: /\binterface\s+ServiceRequest\s*\{[^}]*name\s*:\s*string[^}]*priority\s*:\s*number/, ignoreStrings: true },
      { filePath: 'main.ts', label: 'Type the request array', pattern: /\brequests\s*:\s*ServiceRequest\s*\[\s*\]\s*=/, ignoreStrings: true },
      { filePath: 'main.ts', label: 'Sort highest priority first', pattern: /\.sort\s*\(\s*\(?\s*\w+\s*,\s*\w+\s*\)?\s*=>\s*\w+\.priority\s*-\s*\w+\.priority\s*\)/, ignoreStrings: true },
      { filePath: 'main.ts', label: 'Print request names', pattern: /\.forEach\s*\([^)]*=>[^)]*console\.log\s*\([^)]*\.name/s, ignoreStrings: true },
    ],
    expectedOutput: 'Password reset\nAddress update\nCard question',
  },
]
